### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by ctr1128** [ProjectTako/ffxi-addons#11]
Using windower, getting this error message whenever I try to load the file:

equipviewer: Lua syntax error: equipviewer/equipviewer.lua:7: unexpected symbol near '<'

I'm guessing there's an additional or missiong '<' some where in the code?

**Comment by ctr1128** [comment]
@Renebro no dice yet, just have done the normal troubleshooting of redownloading and reinstalling everything.

**Comment by ProjectTako** [comment]
Generally a message like 'equipviewer: Lua syntax error: equipviewer/equipviewer.lua:7: unexpected symbol near '<'' happens if you try to copy-paste the file from Github, as sometimes Github will have 'garbage data' in it for line numbers, code highlighting, etc. 

If you want to go the copy-paste route, when you go to the file, near the top right there should be a button labeled 'Raw', which will remove any of the data that can mess with it. I however, recommend going to the main page of the ffxi-addons repo, where you will see a green button near the top labeled "Clone or Download", which will give you the option to download everything as a zip. From there you can just take the files you need.

I personally just downloaded as a zip, replaced the files in my addons folder with those of the zip, and was able to successfully load. Please try downloading the repository as a zip, and using those files, rather than the copy-paste method. If you're still having trouble after that, let me know.

**Comment by theblackdeath** [comment]
I’ll backup my working copy and try downloading a fresh copy to see if I can re create the issue when I wake up.

**Comment by ctr1128** [comment]
@ProjectTako Downloaded and replaced the files with the 'Raw' ones, working now! Thank you for the quick response!

@Renebro The authors suggested worked for me, hopefully it works for you as well!
