### ISSUE TITLE
[Windower] Scanzone and targetinfo addon

### ISSUE THREAD

**Issue by xxxKaiserxxx** [ProjectTako/ffxi-addons#2]
Hello,

I'm trying to figure out how to use this addon with [targetinfo addon](https://github.com/Windower/Lua/tree/dev/addons/targetinfo) but no luck.

By using targetinfo addon I can get the hex id for the mob in front of me (which has %59 HP) then i type in-game this command:

//sz scan 100715E

and then I get this error in my console:

lua runtime error: scanzone/scanzone.lua:25: bad argument #6 to 'char' (invalid value)

I tried to use the last 2 digits (5E) but I get this result in my chat log:

Found Entity: 16805892
Name: (long numbers like 798465435135498465415)
Position: ()
HPP: 100 (it should be 59 because I hit the mob to make sure i'm getting the right result)
Status: 1 

Anyway to make this work or make it easier for us players?

I really like this addon and i hope you can help me to make it work.

Thank you, Tako.

**Comment by ProjectTako** [comment]
Kaiser,

You're correct that you needed to use the target index (server id & 0xFF) and not the server id (0x100715E). It sounds like you're getting a proper response, since it's printing the data, but there may be something wrong with the target index you're using. 

Are you using the Windower, or Ashita version? What zone were you in? I will go to the same zone and use the same command you used and see if I can recreate the problem.

**Comment by xxxKaiserxxx** [comment]
Hi,

I'm using windower.

This is my hex id setting in the targetinfo addon (I feel i need to change the %.3X but i'm not a programmer, so... xD):

`if settings.ShowHexID then
        properties:append('Hex ID: ${hex|-|%.3X}')`

I'm using only the hex id in-game and everything else i set it to false in my setting file.

I tried it a few min's ago in (Fei'Yin), I used HomePoint #2 and targeted the 1st mob I saw (Hellish Weapon). The hex id from the targetinfo addon is this: 
10CC0E7

I hit it twice to lower it's HP then tried to scanzone the hex id above but didn't work then I used E7 and the result was for another mob because the HP was @ %100.

I feel i'm doing something wrong but idk what exactly ><

Thank you, Tako.

**Comment by ProjectTako** [comment]
Kaiser,

I'm not exactly sure what is going on for you. I went to the same area and did a scanzone for E7, and everything worked correctly. Below, is a screenshot on what happens when I did //sz scan E7:

![image](https://user-images.githubusercontent.com/5255628/35585918-451fd41a-05c7-11e8-9c88-2ada0657e2ca.png)


Make sure you have the most up to date version of the file.

**Comment by ProjectTako** [comment]
Kaiser,

I pushed an update after reading your post to the windower version of scanzone. I was lazy about it before (since I don't use Windower myself) and didn't add in checking to see if the updatemask was actually containing updates for information such as the name, etc. This should hopefully change it from printing numbers (potential garbage data) to the name, but I was never actually able to recreate the number printing. It was either printing the name, such as my first screenshot, or no name at all (when it didn't have the information in the packet).

The HPP should be the current HPP of the mob. You can see in my screenshots below, the first //sz command, HPP: 100 and then I use a Quick Draw, bringing it to 91%, and the second //sz command, you see HPP: 91. You can see that the second command, the name is blank, and that's just because it wasn't sent in the entity update packet.

Status can mean a couple of things. I have never mapped them all out, but 0, 1, and 7 are the major ones you'll see.  They're like idle, engaged and dead if I remember correctly.

SS:
![image](https://user-images.githubusercontent.com/5255628/35592875-5845c88c-05dc-11e8-80d4-c970e437d199.png)

**Comment by xxxKaiserxxx** [comment]
Thank you thank you thank you so much /bow

It does work now :D 

There is a small issue if you wanna fix/update it (or you can leave it as is if you are lazy xD i can live with it).

 I get the blank name only when i target the mob and do the search at the same time and all the other values are 000 like hp. but if i do it without targeting the mob all the date print just fine.

The status numbers from what i see in my log it seems mean this:

0 engaged (i'm not sure of this because all the data print 0 when i do the search while targeting the mob)
1 idle
7 dead

Thank you so much again, Tako <3 I really appreciate it. /bow

**Comment by ProjectTako** [comment]
Kaiser,

Glad you got it working. I wasn't aware about the targeting thing, since generally I scan for things really far away so that I can position warp to them haha. I'll see if there's something I can do anything about it. Let me know if you have any other issues. 

-Tako
